### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by varnita619**
added home page

### CODE REVIEW

**Comment by pritam-kr** [comment]
Hey UI looks clean.

**Comment by pritam-kr** [comment]
Suggestion you can Improve more card shadow.

**Review by pritam-kr — APPROVED** [review]

**Review by shilpe26 — APPROVED** [review]
▪️Code is clean
▪️Code is properly intended and well structured
▪️Good to merge

**Comment by varnita619** [comment]
> Suggestion you can Improve more card shadow.

Done

**Pull request merged**
